#!/bin/sh

#VMSIZE?=	5120m
#VMFS?=		ufs
#SWAPSIZE?=	1g
#VMBASE?=	vm

# Should be enough for base image, image can be resized in needed
export VMSIZE=8g

# Set to a list of third-party software to enable in rc.conf(5).
export VM_RC_LIST="auditd freebsd-ci"

# Install packages needed by tests:
# coreutils: bin/date
# gdb: local/kyua/utils/stacktrace_test
# jq: sys/net/if_bridge_test
# kyua: everything
# ksh93: tests/sys/cddl/zfs/...
# nist-kat: sys/opencrypto/runtests
# nmap: sys/netinet/fibs_test:arpresolve_checks_interface_fib
# perl5: lots of stuff
# pkgconf: local/lutok/examples_test, local/atf/atf-c, local/atf/atf-c++
# py-dpkt: sys/opencrypto/runtests
# python3: sys/opencrypto/runtests
# devel/py-pytest: sys/net/routing, tests in python in general
# sudo: tests/sys/cddl/zfs/tests/delegate/...
# tcptestsuite: network stack test suite
export VM_EXTRA_PACKAGES="coreutils gdb	jq ksh93 nist-kat nmap perl5 net/py-dpkt net/scapy python python3 devel/py-pytest sudo tcptestsuite"

if [ "${TARGET}" = "amd64" ]; then
    export VM_EXTRA_PACKAGES="$VM_EXTRA_PACKAGES linux-c7-ltp"
fi

vm_extra_pre_umount() {
    cat << EOF >> ${DESTDIR}/boot/loader.conf
autoboot_delay=1
beastie_disable="YES"
loader_logo="none"
console="comconsole,vidconsole"
net.fibs=3
net.inet.ip.fw.default_to_accept=1
mac_bsdextended_load="YES"
vfs.zfs.arc_max=4294967296
EOF
    cat << EOF >> ${DESTDIR}/etc/kyua/kyua.conf
test_suites.FreeBSD.ci = 'true'
test_suites.FreeBSD.fibs = '1 2'
test_suites.FreeBSD.allow_sysctl_side_effects = '1'
test_suites.FreeBSD.cam_test_device = '/dev/ada0'
test_suites.FreeBSD.disks = '/dev/vtbd2 /dev/vtbd3 /dev/vtbd4 /dev/vtbd5 /dev/vtbd6'
EOF
    cat << EOF >> ${DESTDIR}/etc/rc.conf
kld_list=""				# Load modules needed by tests
kld_list="${kld_list} blake2"		# sys/opencrypto
kld_list="${kld_list} cryptodev"	# sys/opencrypto
kld_list="${kld_list} fusefs"		# sys/fs/fusefs
kld_list="${kld_list} ipsec"		# sys/netipsec
kld_list="${kld_list} mac_portacl"	# sys/mac/portacl
kld_list="${kld_list} mqueuefs"		# sys/kern/mqueue_test
kld_list="${kld_list} pfsync"		# sys/netpfil/pf (loads pf)
kld_list="${kld_list} pflog"		# sys/netpfil/pf
kld_list="${kld_list} ipl"		# sys/sbin/ipf (loads ipfilter)
kld_list="${kld_list} ipfw"		# sys/netpfil/ipfw (loads ipfw)
kld_list="${kld_list} ipfw_nat"		# sys/netpfil/ipfw (loads ipfw_nat)
kld_list="${kld_list} ipdivert"		# sys/netinet (loads ipdivert)
kld_list="${kld_list} dummynet"		# sys/netpfil/common
kld_list="${kld_list} carp"		# sys/netinet/carp
kld_list="${kld_list} if_stf"		# sys/net/if_stf
background_fsck="NO"
sendmail_enable="NONE"
cron_enable="NO"
syslogd_enable="NO"
newsyslog_enable="NO"
firstboot_ci_enable="YES"
EOF
    cat <<EOF >> ${DESTDIR}/etc/sysctl.conf
kern.cryptodevallowsoft=1
kern.ipc.tls.enable=1
net.add_addr_allfibs=0
security.mac.bsdextended.enabled=0
vfs.aio.enable_unsafe=1
vfs.usermount=1
EOF
    cat <<EOF >> ${DESTDIR}/etc/fstab
fdesc                      /dev/fd fdescfs   rw      0       0
EOF
    mkdir -p ${DESTDIR}/usr/local/etc/rc.d
    echo $scriptdir
    cp -p ${scriptdir}/../../ci/scripts/test/rc/firstboot_ci ${DESTDIR}/usr/local/etc/rc.d/
    cp -p ${scriptdir}/../../ci/scripts/test/rc/rc.local ${DESTDIR}/etc
    touch ${DESTDIR}/firstboot

    return 0
}
